"""Smoke tests: end-to-end compile with stub author, then static checks on the markdown.

These don't depend on plan-orchestrator being installed; they only verify that the compiler
runs cleanly on a synthetic input and emits a markdown_playbook_v1-shaped file.
"""

from __future__ import annotations

import json
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory

from automation.gstack_to_markdown_playbook_v1.cli import main


_TINY_DESIGN = """
# Design: Tiny demo

Generated by /office-hours on 2026-05-15
Status: APPROVED

## Problem Statement

The user wants a tiny demo playbook for the compiler smoke test.

## Constraints

- Must be small.
- Must be deterministic.

## Recommended Approach

Use the compiler stub author to produce a baseline scope-lock row.
"""


class CompilerSmokeTest(unittest.TestCase):
    def test_dry_run_end_to_end(self):
        with TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            design = tmp_path / "docs" / "gstack" / "design.md"
            design.parent.mkdir(parents=True)
            design.write_text(_TINY_DESIGN, encoding="utf-8")
            out = tmp_path / "docs" / "playbooks" / "demo.playbook.md"
            rc = main([
                "compile",
                "--repo-root", str(tmp_path),
                "--design", str(design),
                "--out", str(out),
                "--dry-run",
            ])
            self.assertEqual(rc, 0)
            self.assertTrue(out.is_file())
            content = out.read_text(encoding="utf-8")
            # Must contain all six required H2 anchor headers.
            for heading in [
                "## 1. Plan Context",
                "## 2. Ordered Execution Plan",
                "## 3. Phase Details",
                "## 4. Shared Guidance",
                "## 5. Risks And Contingencies",
                "## 6. Immediate Next Actions",
            ]:
                self.assertIn(heading, content)
            # The table must include all 11 mandatory columns by header name.
            for col in (
                "step_id", "phase", "action", "why_now", "owner_type",
                "prerequisites", "repo_surfaces", "deliverable", "exit_criteria",
                "allowed_write_roots", "requires_red_green",
            ):
                self.assertIn(col, content, f"missing required column {col!r} in header")
            # Provenance header.
            self.assertIn("playbook_contract: markdown_playbook_v1", content)
            self.assertIn("compiled_by: gstack_to_markdown_playbook_v1", content)
            # Sidecars exist.
            meta = out.with_name("demo.playbook.meta.json")
            validation = out.with_name("demo.validation.json")
            self.assertTrue(meta.is_file())
            self.assertTrue(validation.is_file())
            report = json.loads(validation.read_text(encoding="utf-8"))
            self.assertEqual(report["status"], "pass")
            self.assertEqual(report["schema_version"], "compiler_validation_report_v1")


if __name__ == "__main__":
    unittest.main()
